### PR TITLE
fix(analyze): ignore conmments for imports detection

### LINKED ISSUE #153: `findStaticImports` and `findDynamicImports` do not respect comments
### Environment

**mlly**: ^1.1.1
**node**: 18.14.2

### Reproduction

```ts
import { findDynamicImports, findStaticImports } from "mlly"

console.log(findDynamicImports("// const foo = await import('bar')").length) // returns 1
console.log(findStaticImports("// import { foo } from 'bar' ").length) // returns 1
```

### Describe the bug

Similar to `findExports` before https://github.com/unjs/mlly/pull/56 was merged, imports that have been commented out are still being parsed.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by lishaobos**
fix  #153 

fix https://github.com/antfu/unplugin-auto-import/issues/332

### CODE REVIEW

**Review by pi0 — APPROVED** [review]
LGTM!

File: src/_utils.ts [hunk 1]
```diff
@@ -28,15 +28,22 @@ export function isObject(value) {
 }
 
 export function matchAll(regex, string, addition) {
-  const matches = [];
-  for (const match of string.matchAll(regex)) {
-    matches.push({
+  const comments = [...string.matchAll(/\/\/.*|\/\*[\S\s]*?\*\//g)].map(
```
Comment (danielroe) [inline src/_utils.ts:31]: Just noting that this will also match things like URLs and comments within strings:

```js
const start = "/*"
import foo from 'bar' // <- this will be ignored
const end = "*/"

// everything after start of the url will be ignored
const b = url === "https://test.com" ? await import("something") : await import("something-else")
```

Comment (antfu) [reply src/_utils.ts:31]: Regex is not enough to handle those cases, and that's why we made https://github.com/antfu/strip-literal for Vite and unimport. I remember we had a discussion about having it

Comment (antfu) [reply src/_utils.ts:31]: https://github.com/unjs/mlly/pull/56 this one. Maybe we could reuse it?

Comment (danielroe) [reply src/_utils.ts:31]: Nice solution 👍 Even if there are some downsides (I think tokenizer sometimes fails - so we should wrap in try/catch) it should still be a good improvement.

Comment (pi0) [reply src/_utils.ts:31]: Thanks for reviewing! Good points both.

Suggestions:
- Maybe we can make regex more lean in them meanwhile (only comments in start of the lines to be ignored)
- Fully agree to make similar improvement of #56 to imports i think we mentioned it but was forgotten. If you want to work on it @antfu ❤️

Comment (lishaobos) [reply src/_utils.ts:31]: what a genius!

but how about this comments reg: (?<!['"`])\/\/.*|(?<!['"`])\/\*(?:(?!\/\*|\*\/)["'\s\S])*\*\/(?<!\*\/['"`])

**Comment by lishaobos** [comment]
image

what happend? i alaways build successed and i can not find the word in the code.

image
image
image

**Comment by lishaobos** [comment]
it is branch not right? 😄😄😄

**Comment by lishaobos** [comment]
@danielroe hi, i fixed the merge error.

https://github.com/unjs/mlly/actions/runs/4392442503/jobs/7692420749#step:2:204

image

**Review by pi0 — APPROVED** [review]
Amazing work and refactors thanks 💯
